id: P001834
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:24:36.836850
source_metadata:
  id: bdr:W12486
  title: བརྡ་གསར་རྙིང་གི་ཁྱད་པར་ལི་ཤིའི་གུར་ཁང་།
  author: ''
  volumes:
    0a304e0c2d834668bd21b2c8bbb98e08:
      image_group_id: I1KG23692
      title: ''
      volume_number: 1
      total_pages: 82
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
