id: P001834
initial_creation_type: ocr
source_metadata:
  id: bdr:W12486
  title: བརྡ་གསར་རྙིང་གི་ཁྱད་པར་ལི་ཤིའི་གུར་ཁང་།
  author: ''
  volumes:
    0a304e0c2d834668bd21b2c8bbb98e08:
      image_group_id: I1KG23692
      title: ''
      volume_number: 1
      total_pages: 82
